#!/usr/bin/env bash
set -euo pipefail

echo "🚀 Setting up your tmux environment..."

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ----- helpers -----
have() { command -v "$1" >/dev/null 2>&1; }

SUDO=""
if [ "${EUID:-$(id -u)}" -ne 0 ] && have sudo; then
  SUDO="sudo"
fi

detect_pm() {
  if have apt-get; then echo apt; return; fi
  if have dnf; then echo dnf; return; fi
  if have yum; then echo yum; return; fi
  if have pacman; then echo pacman; return; fi
  if have brew; then echo brew; return; fi
  if have zypper; then echo zypper; return; fi
  if have apk; then echo apk; return; fi
  if have port; then echo port; return; fi
  echo none
}

install_pkg() {
  local pm="$1"; shift
  local pkgs=("$@")
  case "$pm" in
    apt)
      $SUDO apt-get update -y || true
      $SUDO apt-get install -y "${pkgs[@]}" ;;
    dnf)
      $SUDO dnf install -y "${pkgs[@]}" ;;
    yum)
      $SUDO yum install -y "${pkgs[@]}" ;;
    pacman)
      $SUDO pacman -Sy --noconfirm "${pkgs[@]}" ;;
    brew)
      brew install "${pkgs[@]}" ;;
    zypper)
      $SUDO zypper install -y "${pkgs[@]}" ;;
    apk)
      $SUDO apk add --no-cache "${pkgs[@]}" ;;
    port)
      $SUDO port install "${pkgs[@]}" ;;
    *)
      return 1 ;;
  esac
}

PM=$(detect_pm)

# ----- ensure prerequisites -----
for cmd in git tmux; do
  if ! have "$cmd"; then
    echo "📦 Installing missing dependency: $cmd"
    if [ "$PM" != "none" ]; then
      if ! install_pkg "$PM" "$cmd"; then
        echo "⚠️  Failed to install $cmd automatically. Please install it and re-run."
      fi
    else
      echo "⚠️  No supported package manager detected. Please install $cmd manually."
    fi
  fi
done

if ! have zsh; then
  echo "📦 zsh not found; attempting to install (used as default shell)"
  if [ "$PM" != "none" ]; then
    install_pkg "$PM" zsh || true
  else
    echo "ℹ️  Proceeding without zsh install; your current shell will be used."
  fi
fi

# Determine best shell path for tmux default-shell/command
SHELL_PATH="$(command -v zsh || true)"
if [ -z "$SHELL_PATH" ]; then
  SHELL_PATH="${SHELL:-/bin/bash}"
fi

# ----- TPM setup -----
DEST_TPM="$HOME/.tmux/plugins/tpm"
mkdir -p "$(dirname "$DEST_TPM")"

if [ -d "$REPO_DIR/plugins/tpm" ]; then
  # Use bundled TPM (submodule) if present
  if [ ! -e "$DEST_TPM" ]; then
    echo "🔗 Linking TPM plugin manager"
    ln -sf "$REPO_DIR/plugins/tpm" "$DEST_TPM"
  fi
else
  # Fallback: clone TPM directly
  if [ ! -d "$DEST_TPM/.git" ]; then
    echo "📥 Cloning TPM plugin manager"
    if have git; then
      git clone https://github.com/tmux-plugins/tpm "$DEST_TPM" || true
    fi
  fi
fi

# Init submodules if available
if [ -d "$REPO_DIR/.git" ]; then
  echo "📦 Initializing plugin submodules"
  git -C "$REPO_DIR" submodule update --init --recursive || true
fi

# ----- Write ~/.tmux.conf wrapper -----
TMUX_CONF="$HOME/.tmux.conf"
if [ -e "$TMUX_CONF" ] && ! grep -q "Auto-generated by tshmux" "$TMUX_CONF"; then
  cp "$TMUX_CONF" "$TMUX_CONF.bak.$(date +%s)"
  echo "💾 Backed up existing ~/.tmux.conf"
fi

echo "🧩 Writing ~/.tmux.conf"
cat > "$TMUX_CONF" <<EOF
# Auto-generated by tshmux install.sh
source-file "$REPO_DIR/tmux.conf"
set-option -g default-shell "$SHELL_PATH"
set-option -g default-command "$SHELL_PATH"
EOF

# ----- Install plugins non-interactively -----
if [ -x "$DEST_TPM/bin/install_plugins" ]; then
  echo "🔌 Installing tmux plugins via TPM"
  if ! "$DEST_TPM/bin/install_plugins"; then
    echo "⚠️  Plugin install encountered an issue. You can retry inside tmux with prefix + I."
  fi
else
  echo "ℹ️  TPM install script not found. Inside tmux, press prefix + I to install plugins."
fi

echo "✅ All set! Start tmux with: tmux"
